title: Jerry Balloch # your name (or website title) here
logo: "/images/jb_logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recent graduate of CodeClan’s Data Analysis bootcamp looking to use the knowledge gained on the course while continuing to learn in the industry.
 

theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
